import fs from "fs/promises";
import path from "path";
import { validateProjectPath } from "../utils/validation.js";
import { Errors } from "../utils/errors.js";
import { HandlerResponse } from "../types/index.js";

type ProjectArgs = { projectPath: string };
type WritePluginCodeArgs = ProjectArgs & { filename: string; code: string };
type UpdatePluginsConfigArgs = ProjectArgs & { plugins: unknown[] };

export async function writePluginCode(args: WritePluginCodeArgs): Promise<HandlerResponse> {
    const { projectPath, filename, code } = args;
    await validateProjectPath(projectPath);

    if (!filename.endsWith(".js")) {
        throw Errors.invalidParameter("filename", "Plugin filename must end with .js");
    }

    const pluginsDir = path.join(projectPath, "js", "plugins");
    try {
        await fs.mkdir(pluginsDir, { recursive: true });
    } catch (e: unknown) {
        // Ignore if exists
    }

    const filePath = path.join(pluginsDir, filename);
    await fs.writeFile(filePath, code, "utf-8");

    return {
        content: [
            {
                type: "text",
                text: `Successfully wrote plugin code to ${filename}`,
            },
        ],
    };
}

export async function getPluginsConfig(args: ProjectArgs): Promise<HandlerResponse> {
    const { projectPath } = args;
    await validateProjectPath(projectPath);

    const pluginsConfigPath = path.join(projectPath, "js", "plugins.js");

    try {
        const content = await fs.readFile(pluginsConfigPath, "utf-8");
        const match = content.match(/var\s+\$plugins\s*=\s*(\[[\s\S]*?\])\s*;/);
        if (!match) {
            throw Errors.dataFileReadError("plugins.js", "Could not parse plugins.js format");
        }
        const pluginsJson = match[1];
        JSON.parse(pluginsJson);

        return {
            content: [
                {
                    type: "text",
                    text: pluginsJson,
                },
            ],
        };
    } catch (error: unknown) {
        const err = error as NodeJS.ErrnoException;
        if (err?.code === 'ENOENT') {
            return {
                content: [
                    {
                        type: "text",
                        text: "[]",
                    },
                ],
            };
        }
        throw error;
    }
}

export async function updatePluginsConfig(args: UpdatePluginsConfigArgs): Promise<HandlerResponse> {
    const { projectPath, plugins } = args;
    await validateProjectPath(projectPath);

    const pluginsConfigPath = path.join(projectPath, "js", "plugins.js");
    const content = `// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
${JSON.stringify(plugins, null, 2)};
`;

    await fs.writeFile(pluginsConfigPath, content, "utf-8");

    return {
        content: [
            {
                type: "text",
                text: "Successfully updated plugins.js",
            },
        ],
    };
}
